CREATE SCHEMA IF NOT EXISTS hrms;
CREATE TABLE IF NOT EXISTS hrms.employees (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(128) NOT NULL,
  dept VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL
);
