CREATE SCHEMA IF NOT EXISTS sales;
CREATE TABLE IF NOT EXISTS sales.invoices (
  id SERIAL PRIMARY KEY,
  invoice_no VARCHAR(64) UNIQUE NOT NULL,
  customer VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL,
  due DATE NOT NULL,
  amount NUMERIC(12,2) NOT NULL
);
