server:
  port: 9100

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/erp
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 4
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  flyway:
    enabled: true
    schemas: reporting

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    access-ttl: 3600

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    display-operation-id: true
    try-it-out-enabled: true
