CREATE SCHEMA IF NOT EXISTS orders;
CREATE TABLE IF NOT EXISTS orders.sales_orders (
  id SERIAL PRIMARY KEY,
  code VARCHAR(64) UNIQUE NOT NULL,
  customer VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL,
  total NUMERIC(12,2) NOT NULL,
  order_date DATE NOT NULL
);
