CREATE SCHEMA IF NOT EXISTS users;
CREATE TABLE IF NOT EXISTS users.user_profiles (
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    full_name VARCHAR(255),
    role VARCHAR(50) NOT NULL
);
