-- Initialize auth schema, users table, trigger, and seed admin/user accounts

-- 1) Create schema
CREATE SCHEMA IF NOT EXISTS auth;

-- 2) Create users table
CREATE TABLE IF NOT EXISTS auth.users (
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(200) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  roles VARCHAR(200) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3) Trigger to update updated_at
CREATE OR REPLACE FUNCTION auth.auth_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_auth_users_set_updated_at ON auth.users;
CREATE TRIGGER trg_auth_users_set_updated_at
BEFORE UPDATE ON auth.users
FOR EACH ROW EXECUTE PROCEDURE auth.auth_set_updated_at();

-- 4) Enable pgcrypto (for bcrypt hashing)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 5) Seed admin and user accounts using bcrypt hashes generated by pgcrypto
-- admin / admin
INSERT INTO auth.users (username, password, enabled, roles)
VALUES ('admin', crypt('admin', gen_salt('bf', 10)), TRUE, 'ROLE_ADMIN')
ON CONFLICT (username) DO UPDATE
  SET password = EXCLUDED.password,
      enabled = EXCLUDED.enabled,
      roles = EXCLUDED.roles;

-- user / user
INSERT INTO auth.users (username, password, enabled, roles)
VALUES ('user', crypt('user', gen_salt('bf', 10)), TRUE, 'ROLE_USER')
ON CONFLICT (username) DO NOTHING;
