CREATE SCHEMA IF NOT EXISTS enquiry;
CREATE TABLE IF NOT EXISTS enquiry.enquiries (
  id SERIAL PRIMARY KEY,
  code VARCHAR(64) UNIQUE NOT NULL,
  customer VARCHAR(255) NOT NULL,
  channel VARCHAR(64) NOT NULL,
  subject VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL
);
