CREATE SCHEMA IF NOT EXISTS products;
CREATE TABLE IF NOT EXISTS products.items (
  id SERIAL PRIMARY KEY,
  sku VARCHAR(64) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  stock INT NOT NULL DEFAULT 0,
  reorder INT NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL
);
