CREATE SCHEMA IF NOT EXISTS finance;
CREATE TABLE IF NOT EXISTS finance.transactions (
  id SERIAL PRIMARY KEY,
  tx_date DATE NOT NULL,
  account VARCHAR(64) NOT NULL,
  tx_type VARCHAR(32) NOT NULL,
  amount NUMERIC(12,2) NOT NULL,
  memo VARCHAR(255)
);
